// Chapter 3
// Question 4
//
// Write a program that converts X degrees fahrenheit (f) to degrees (c) using the following formula: 
// c = (f - 32) / 1.8
//

#include <stdio.h>

int main(int argc, const char * argv[]) {
    float c, f;
    printf("Enter the temperature in fahrenheit.\n");
    scanf("%f", &f);
    c = (f - 32) / 1.8;
    printf("%f degrees fahrenheit is equal to %f degrees celsius.\n", f, c);
    return 0;
}

// Question 6 
//
// Write a program to evaluate the polynomial shown here:
// 3x^3 - 5x^2 + 6
// for x=2.55
// 

#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    float x, y;
    x = 2.55;
    y = 3*(x * x * x) - 5*(x * x) + 6;
    printf("The polynomial is equal to %f.\n", y);
    return 0;
}

// Chapter 4 (page 63)
// Question 2
//
// Write a program to generate and display a table of n and n^2, for integer values of n ranging from 1 to 10.
// Be certain to print appropriate column headings.
//
//

#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    int n, x;
    printf(" n  | n^2\n");
    printf("----------\n");
    for (n=1; n<10; ++n) {
        x = n*n;
        printf(" %i  |  %i\n", n, x);
    }
    return 0;
}


// Question 3
//
// A triangular number can be generated by the formula:
//
// triangularnumber = n (n+1) / 2
// 
// for any integer value of n. For example, the triangular number 55 can be generated by substituting 10 as the
// value for n in the preceding formula. Write a program that generates a table of triangular numbers using the
// preceding formula. Have the program generate every fifth triangular number between 5 and 50 (that is, 5, 10, 15,...50).
// 

#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    int n, t;
    for (n=1; n<10; ++n) {
        t = n*(n+1)/2;
        printf("The triangular number is: %i\n", t);
    }
    return 0;
}


// Question 4
//
// The factorial of an integer n, the written n!, is the product of the consecutive integers 1 through n. For example,
// 5 factorial is calculated as:
// 
// 5! = 5 x 4 x 3 x 2 x 1 = 120
// 
// Write a program to generate and print a table of the first 10 factorials. 
// 

#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    int n;
    int f = 1;
    printf("n  |  n!\n");
    printf("--------\n");
    for(n=1; n<11; ++n) {
        f = f*n;
        printf("%i  |  %i\n", n, f);
    }
    return 0;
}


// Questions 5 - 10
// In book, worth doing. Based on the book examples. 7, 8, and 9 look great. 

// Question 7
//
// #include <stdio.h>
//
// int main(int argc, const char * argv[]) {
//    
//    int x, y;
//    printf("Enter the first number:\n");
//    scanf("%i", &x);
//    printf("Enter the second number:\n");
//    scanf("%i", &y);
//
//    printf("$%i.%.5i\n\n", x, y);
//    
//    return 0;
// }

// Returns:

Enter the first number:
x
Enter the second number:
y
$x.0000y


// Question 8
// Old Program:
//

// #include <stdio.h>

// int main(int argc, const char * argv[]) {
    
//     int n, i, number, triangularNumber;
    
//     for (i=1; i<=5; ++i) {
//         printf("What triangular number do you want?\n");
//         scanf("%i", &number);
        
//         triangularNumber = 0;
        
//         for (n=1; n<=number; ++n)
//             triangularNumber += n;
            
//             printf("Triangular number %i is %i.\n\n", number, triangularNumber);
//     }
    
//     return 0;
// }

// New program:
//

#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    int b, n, i, number, triangularNumber;
    
    printf("How many triangular numbers do you want to calculate?\n");
    scanf("%i", &b);
    
    for (i=1; i<=b; ++i) {
        printf("What triangular number do you want?\n");
        scanf("%i", &number);
        
        triangularNumber = 0;
        
        for (n=1; n<=number; ++n)
            triangularNumber += n;
            
            printf("Triangular number %i is %i.\n\n", number, triangularNumber);
    }
    
    return 0;
}


// Question 9
// While Loops
//


// Section 4.5
// Had some trouble with the second for loop, will try again later.
//

#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    int n, i, number, triangularNumber;
    
    while (i<=5) {
        printf("What triangular number do you want?\n");
        scanf("%i", &number);
        
        triangularNumber = 0;
        
        for (n=1; n<=number; ++n)
            triangularNumber += n;
            
            printf("Triangular number %i is %i.\n\n", number, triangularNumber);
        ++i;
    }
    
    return 0;
}


// Question 11
//
// Write a program that calculates the sum of the digits in an integer. For example, the sum of the digits in the 
// number 2155 is 2 + 1 + 5 + 5 or 13. The program should accept any arbitrary integer typed in by the user. 
// 
// Hint: This can be done with a while loop. 
// 


#include <stdio.h>

int main(int argc, const char * argv[]) {
    
    int n, remainder, sum = 0;
    
    printf("Enter your number:\n");
    scanf("%i", &n);
    
    while (n != 0) {
        remainder = n % 10;
        sum = sum + remainder;
        n = n / 10;
    }
    printf("%i\n", sum);

    
    return 0;
}
 